# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb5c40ced88230d98c7dec82abd98ad6dc12c2b8bcbf175c8a62599486ffcb9c31ffee265e298242a15a012279c772d1abf45843f1ed6f3fc4dcba99b276516d

test:
  secret_key_base: 80a68189eedb1a70f1462042caa1a96d6ca9646e15e9a3ebd0d0605a22b5726fbd91563a5b4f3d4797e68b2487b9ec2450f5caeb998d4b73fd25e10f69a29783

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
